import { Product, Category } from '@/types';

export const categories: Category[] = [
  {
    id: 'led-bulb',
    name: 'LED Bulbs',
    icon: 'Lightbulb',
    description: 'Energy-efficient bulbs for every space',
    productCount: 48,
  },
  {
    id: 'tube-light',
    name: 'Tube Lights',
    icon: 'Minus',
    description: 'Slim and bright linear lighting',
    productCount: 32,
  },
  {
    id: 'sensor-light',
    name: 'Sensor Lights',
    icon: 'Eye',
    description: 'Motion-activated smart lighting',
    productCount: 24,
  },
  {
    id: 'radar-sensor',
    name: 'Radar Sensor',
    icon: 'Radar',
    description: 'Advanced microwave detection lighting',
    productCount: 16,
  },
  {
    id: 'panel-light',
    name: 'Panel Lights',
    icon: 'LayoutGrid',
    description: 'Sleek recessed ceiling panels',
    productCount: 28,
  },
  {
    id: 'flood-light',
    name: 'Flood Lights',
    icon: 'Sun',
    description: 'High-power outdoor illumination',
    productCount: 20,
  },
];

export const products: Product[] = [
  {
    id: 'ee-led-001',
    name: 'GlowPro 12W Smart LED',
    category: 'led-bulb',
    price: 299,
    wattage: '12W',
    lumens: '1200 lm',
    lifespan: '50,000 hrs',
    colorTemp: '3000K-6500K',
    description: 'Smart LED bulb with app control and 16 million colors.',
    features: ['Wi-Fi Enabled', 'Voice Control', 'Dimmable', 'Energy Star'],
    image: '/images/led-bulb-1.jpg',
    badge: 'Bestseller',
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'ee-tube-001',
    name: 'LinearPro 20W T5 Tube',
    category: 'tube-light',
    price: 449,
    wattage: '20W',
    lumens: '2200 lm',
    lifespan: '40,000 hrs',
    colorTemp: '4000K Cool White',
    description: 'Ultra-slim T5 tube with flicker-free technology.',
    features: ['Flicker-Free', 'Instant Start', 'Mercury-Free', '5yr Warranty'],
    image: '/images/tube-light-1.jpg',
    rating: 4.6,
    inStock: true,
  },
  {
    id: 'ee-sensor-001',
    name: 'MotionSense PIR 15W',
    category: 'sensor-light',
    price: 599,
    wattage: '15W',
    lumens: '1500 lm',
    lifespan: '35,000 hrs',
    colorTemp: '6000K Daylight',
    description: 'PIR motion sensor light with 120° detection angle.',
    features: ['120° Detection', 'Auto On/Off', 'IP65 Waterproof', 'Adjustable Timer'],
    image: '/images/sensor-light-1.jpg',
    badge: 'New Arrival',
    rating: 4.7,
    inStock: true,
  },
  {
    id: 'ee-radar-001',
    name: 'RadarVue Microwave 18W',
    category: 'radar-sensor',
    price: 899,
    wattage: '18W',
    lumens: '1800 lm',
    lifespan: '45,000 hrs',
    colorTemp: '5000K Natural White',
    description: 'Advanced microwave radar sensor for through-wall detection.',
    features: ['Through-Wall Detection', '360° Coverage', 'Dusk-to-Dawn', 'Anti-Interference'],
    image: '/images/radar-sensor-1.jpg',
    badge: 'Premium',
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'ee-panel-001',
    name: 'SlimFit 24W Panel',
    category: 'panel-light',
    price: 749,
    wattage: '24W',
    lumens: '2400 lm',
    lifespan: '50,000 hrs',
    colorTemp: '4000K-6500K',
    description: 'Edge-lit panel with uniform light distribution.',
    features: ['Edge-Lit Design', 'Anti-Glare', 'Recessed Mount', 'Driver Included'],
    image: '/images/panel-light-1.jpg',
    rating: 4.5,
    inStock: true,
  },
  {
    id: 'ee-flood-001',
    name: 'PowerBeam 50W Flood',
    category: 'flood-light',
    price: 1299,
    wattage: '50W',
    lumens: '5000 lm',
    lifespan: '30,000 hrs',
    colorTemp: '6500K Daylight',
    description: 'Heavy-duty flood light for large area illumination.',
    features: ['Die-Cast Aluminum', 'Tempered Glass', 'Surge Protection', 'Wide Beam Angle'],
    image: '/images/flood-light-1.jpg',
    rating: 4.7,
    inStock: true,
  },
];